[project]
name = "timestamp-clipper-repl"
version = "0.1.0" # uhh...
description = "A little REPL program to extract video/audio at specified timestamps, acting as an ongoing inventory towards doing so, using FFmpeg and written in Python 3"
readme = "README.md"
requires-python = ">=3.10" # for smooth use of type hints :)
dependencies = []

[project.scripts]
app = "timestamp_clipper_repl.main:main"
main = "timestamp_clipper_repl.main:main"
timestamp-clipper-repl = "timestamp_clipper_repl.main:main"
timestamp_clipper_repl = "timestamp_clipper_repl.main:main"

[build-system]
requires = ["uv_build>=0.12,<0.13"]
build-backend = "uv_build"
