[project]
name = "timestamp-clipper-buddy"
version = "1.0.0"
description = "A little REPL program to extract video/audio at specified timestamps, acting as an ongoing inventory towards doing so, using FFmpeg and written in Python 3"
readme = "README.md"
requires-python = ">=3.10" # for smooth use of type hints :)
dependencies = [
    "pathvalidate"
]

[project.scripts]
# entry point: uv run timestamp-clipper-buddy
timestamp-clipper-buddy = "timestamp_clipper_buddy.main:main"

[build-system]
requires = ["uv_build>=0.12"] # whatever works I guess?
build-backend = "uv_build"
